#!/usr/bin/env python3
"""Fail if a workflow runs an action that is not pinned to a commit SHA.

`.github/dependabot.yml` states the rule and the reason: the workflows pin every
action to a commit SHA, because a retargeted `v4` runs attacker-chosen code in a
job that holds a live credential, and Dependabot exists to keep those pins from
rotting. The rule was applied by hand (#96 follow-ups) and kept by memory after
that, so nothing noticed when #472 -- a workflow file generated by the Claude
Code GitHub App installer and merged with both bot reviewers' SHA-pinning
findings unresolved -- put four mutable tags back: `actions/checkout@v4` and
`anthropics/claude-code-action@v1`, twice each, in jobs carrying
`id-token: write` and an OAuth token. Dependabot then did the only thing it
could and offered to move one mutable tag to another (#518). This is the
enforcing half of that fix: the rule now fails a build instead of a reviewer.

WHAT IT CHECKS, which is a SHAPE and not an identity:

  - the ref is a 40-character lowercase hex commit SHA, not a tag or a branch;
  - a trailing comment names a three-part release (`# v7.0.1`), because a bare
    SHA is how a pin rots unrefreshed -- Dependabot reads that comment to know
    what the pin is a pin OF, and every one of this repository's pins carries
    one. A two-part or bare-major comment is refused deliberately: `# v7` names
    a moving pointer rather than the release the SHA is.

WHAT IT CANNOT SEE, stated plainly so the surrounding prose claims no more:

  - whether the SHA IS the release its comment names. That needs the network,
    which a gate cannot have; a comment reading `# v7.0.1` beside some other
    project's commit passes here. Dependabot is what keeps the two honest.
  - whether the pinned commit deserves trust. A pin freezes code; it does not
    review it, and freezing is also how a workflow keeps running a stale action
    long after upstream fixed something in it. That is the cost the pairing with
    Dependabot buys back, and the reason the version comment is mandatory.
  - `persist-credentials: false`, the companion clause of the same policy. Three
    `actions/checkout` call sites lack it today, so a rule for it would go red on
    work this guard is not about; it is a separate rule and needs its own change.
  - a `uses:` written INSIDE a `run: |` block -- a workflow that writes a
    workflow. That text is not an action this repository runs, so it is out of
    scope; it is still refused if it looks like a real reference, because a real
    one landing there is far more likely to be this parser losing its place.
  - anything outside `.github/workflows/`: a composite action's own `uses:`, or a
    reusable workflow held in another repository.

IT READS THE TEXT, NOT THE PARSED YAML, and that is forced rather than chosen:
half the rule lives in a COMMENT, and every YAML parser discards comments on the
way to a value. A parsed `uses:` can say `owner/repo@<sha>` and never say which
release that SHA is. The other guards under this directory read text for their
own reasons; this one has no alternative, and it keeps them all stdlib-only.

EXEMPTIONS, recorded rather than discovered later. Two `uses:` forms can never
carry a commit SHA -- a local action or reusable workflow (`./…`) and a container
(`docker://…`) -- so both pass. Neither exists in this repository today, which
means a guard that flagged them would look correct forever and then go red on the
first legitimate one. A `docker://` image is not required to carry a digest here;
that would be a different rule about a different supply chain.

It self-tests before it scans, because a broken pattern and a clean repository
print the same thing otherwise, and it refuses rather than skips: a line naming
something that looks like an action, which this parser cannot place, stops the
run by name and line instead of passing silently over it.
"""

import pathlib
import re
import subprocess
import sys

WORKFLOWS = pathlib.Path(__file__).resolve().parents[1] / "workflows"

# A `uses:` mapping key, in both spellings that occur: the list-item form that
# opens a step (`- uses: …`) and the keyed form that follows a `- name:` line.
# Anchoring on only the first misses every reference in the two workflows this
# guard was written for, which are all the second.
USES_KEY = re.compile(r"^(?P<indent>[ \t]*)(?:-[ \t]+)?uses:[ \t]*(?P<value>\S.*?)[ \t]*$")

# Deliberately looser, and it must stay that way: it matches what USES_KEY
# cannot, so a reference this parser fails to place is reported rather than
# skipped. The lookbehind is load-bearing -- `causes:` in a comment in
# staging-parked.yml matches a bare `uses:` search, and a guard that flags it
# gets narrowed by whoever fixes that, which is how the real rule goes with it.
USES_TOKEN = re.compile(r"(?<![A-Za-z0-9_])uses:")

# Any key introducing a literal or folded block scalar, not just `run:`. The
# workflows use three (`run:`, `if:`, `additional_permissions:`), and the
# constraint is the same for all of them: their body is data, not YAML mapping
# keys, so a `uses:` inside one is text rather than a step.
BLOCK_SCALAR = re.compile(r"^(?P<indent>[ \t]*)(?:-[ \t]+)?[A-Za-z_][\w.-]*:[ \t]*[|>][-+0-9]*[ \t]*$")

# An action reference that can be pinned: `owner/repo@ref`, with the optional
# subdirectory a composite action or a remote reusable workflow adds.
REFERENCE = re.compile(r"^(?P<action>[\w.-]+/[\w./-]+)@(?P<ref>\S+)$")

# The pin itself. Lowercase because that is what git writes and what every
# existing pin here is; an uppercase SHA resolves fine but would make two
# spellings of one pin, and Dependabot rewrites only the one it wrote.
SHA = re.compile(r"^[0-9a-f]{40}$")

# The release the SHA is. Three parts, anchored at the start of the comment so
# trailing prose is allowed but a leading excuse is not.
RELEASE = re.compile(r"^#[ \t]*v\d+\.\d+\.\d+(?![\w.])")

# The two forms with no SHA to pin. Neither occurs here yet; see the docstring.
EXEMPT = ("./", "docker://")


class Reference:
    """One `uses:` key: where it is, what it names, and what follows it."""

    def __init__(self, line, value, comment):
        self.line = line
        self.value = value
        self.comment = comment


def split_comment(text):
    """A line's value and its trailing comment.

    Splits on the first `#`, which is safe for this key: no action reference,
    ref or release contains one, so anything from there on is the comment.
    """
    hash_at = text.find("#")
    if hash_at < 0:
        return text.rstrip(), ""
    return text[:hash_at].rstrip(), text[hash_at:].strip()


def in_block_scalar(lines):
    """The indexes of lines sitting inside a block scalar's body."""
    inside, i = set(), 0
    while i < len(lines):
        m = BLOCK_SCALAR.match(lines[i])
        if not m:
            i += 1
            continue
        # The body is everything more-indented than the key, blank lines
        # included, up to the first line that returns to the key's column.
        key_indent = len(m.group("indent").expandtabs())
        j = i + 1
        while j < len(lines):
            line = lines[j]
            if line.strip() and len(line) - len(line.lstrip()) <= key_indent:
                break
            inside.add(j)
            j += 1
        i = j
    return inside


def references(name, lines):
    """Every action reference in one workflow, refusing what it cannot place."""
    body = in_block_scalar(lines)
    found = []
    for n, line in enumerate(lines):
        code, comment = split_comment(line)
        if not USES_TOKEN.search(code):
            continue
        where = f"{name}:{n + 1}"
        m = USES_KEY.match(code)
        if n in body:
            # A `uses:` in block-scalar text is shell or an expression, not a
            # step -- unless it parses as a real reference, in which case the
            # likelier reading by far is that this parser lost its place, and
            # a reference it never checked is exactly what it exists to prevent.
            if m and (m.group("value").startswith(EXEMPT)
                      or REFERENCE.match(m.group("value").strip("\"'"))):
                raise SystemExit(
                    f"{where}: this reads as an action reference but sits inside a"
                    " block scalar, where this guard would never check it. Either"
                    " the block-scalar scan has lost its place, or a workflow is"
                    " writing a workflow — in which case say so here."
                )
            continue
        if not m:
            raise SystemExit(
                f"{where}: this names `uses:` in a shape this guard cannot read,"
                " so its pin would go UNCHECKED. Spell it the way the other steps"
                " are, or teach USES_KEY the new shape."
            )
        found.append(Reference(n + 1, m.group("value").strip("\"'"), comment))
    return found


def violation(ref):
    """Why this reference is not an acceptable pin, or None if it is one."""
    if ref.value.startswith(EXEMPT):
        return None
    m = REFERENCE.match(ref.value)
    if not m:
        return f"`{ref.value}` is not an action reference this guard can pin-check"
    if not SHA.match(m.group("ref")):
        return (f"`{m.group('action')}` is pinned to `{m.group('ref')}`, a mutable"
                " ref — a tag or branch can be retargeted onto other code")
    if not RELEASE.match(ref.comment):
        return (f"`{m.group('action')}` is pinned to a commit but names no release"
                " — add a trailing `# vX.Y.Z` so Dependabot can refresh it")
    return None


def scan(name, text):
    """One workflow's violations, as (line, why)."""
    return [(r.line, why) for r in references(name, text.splitlines())
            if (why := violation(r)) is not None]


def selftest():
    """Prove each rule fires and each exemption holds. Documents, not prose.

    The rows are a sample: a rule narrowed to some shape none of them names
    still passes every one. What they prove is that each rule is wired in and
    each exemption is deliberate — and, for the refusals, that a reference this
    parser cannot place stops the run rather than leaving CI green over it.
    """
    step = "    steps:\n      - name: a step\n"
    must_flag = [
        ("a mutable major tag, list-item form",
         "      - uses: actions/checkout@v4\n"),
        ("a mutable major tag, keyed form",
         step + "        uses: anthropics/claude-code-action@v1\n"),
        ("a mutable release tag, which looks pinned and is not",
         "      - uses: actions/checkout@v7.0.1 # v7.0.1\n"),
        ("a branch",
         "      - uses: anthropics/claude-code-action@main\n"),
        ("a short SHA",
         "      - uses: actions/checkout@3d3c42e5 # v7.0.1\n"),
        ("an uppercase SHA, which is a second spelling of one pin",
         "      - uses: actions/checkout@3D3C42E5AAC5BA805825DA76410C181273BA90B1 # v7.0.1\n"),
        ("a SHA with no release named",
         "      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1\n"),
        ("a SHA whose comment names a moving pointer, not a release",
         "      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7\n"),
        ("a SHA whose comment names a two-part version",
         "      - uses: helm/kind-action@ef37e7f390d99f746eb8b610417061a60e82a6cc # v1.14\n"),
        ("a comment that explains before it names the release",
         "      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # pinned, v7.0.1\n"),
    ]
    must_pass = [
        ("a pinned action, list-item form",
         "      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1\n"),
        ("a pinned action, keyed form",
         step + "        uses: anthropics/claude-code-action@fa2b2666b747000bf42767d1f332065b375e3c8f # v1.0.214\n"),
        ("a pinned action, quoted",
         '      - uses: "actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1" # v7.0.1\n'),
        ("a release comment with prose after it",
         "      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1, see #96\n"),
        ("a remote reusable workflow, which pins like an action",
         "    uses: o/r/.github/workflows/w.yml@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1\n"),
        ("a local action, which has no SHA to pin",
         "      - uses: ./.github/actions/thing\n"),
        ("a local reusable workflow",
         "    uses: ./.github/workflows/reusable.yml\n"),
        ("a container, which pins by a different mechanism",
         "      - uses: docker://alpine:3.20\n"),
        ("shell text inside a block scalar",
         "      - run: |\n          grep uses: x.yml\n"),
        ("a comment that merely contains the token",
         "      # it names both causes: this cannot\n"),
        ("a folded block scalar's body",
         "      - if: >\n          contains(github.event.uses: no)\n"),
        ("a block scalar the next key closes",
         "      - run: |\n          echo uses: nothing\n      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1\n"),
    ]
    # Shapes that must stop the run rather than pass or be counted. Each was a
    # way for a reference to go unchecked while the scan still printed `ok`.
    must_refuse = [
        ("a reference this parser cannot place",
         "      - uses:\n          - actions/checkout@v4\n"),
        ("a real reference the block-scalar scan swallowed",
         "      - run: |\n          uses: actions/checkout@v4\n"),
        ("a local action the block-scalar scan swallowed",
         "      - run: |\n          uses: ./.github/actions/thing\n"),
    ]

    failures = []
    for label, text in must_flag:
        try:
            if not scan("selftest.yml", text):
                failures.append(f"MISSED   {label}: {text.strip()}")
        except SystemExit as e:
            failures.append(f"REFUSED  {label}: expected a finding, got {e}")
    for label, text in must_pass:
        try:
            found = scan("selftest.yml", text)
            if found:
                failures.append(f"FLAGGED  {label}: {found}")
        except SystemExit as e:
            failures.append(f"REFUSED  {label}: expected a clean scan, got {e}")
    for label, text in must_refuse:
        try:
            scan("selftest.yml", text)
            failures.append(f"ACCEPTED {label}: expected a refusal, got none")
        except SystemExit:
            pass

    # The parser must also SEE what it passes, or an exemption and a blind spot
    # are the same result. Every must_pass row that names a step is one
    # reference; the four that are comment or block-scalar text are none.
    seen = len(references("selftest.yml", must_pass[0][1].splitlines()))
    if seen != 1:
        failures.append(f"COUNT    a single pinned step read as {seen} references")
    return failures


def workflows():
    """The workflow files, listed twice over so a narrowing of either fails.

    The glob is what the scan walks; git is what the repository says is there.
    Compared for equality rather than for what one of them missed, because the
    ways this guard dies quietly are symmetrical: a file the glob stops matching
    (a `.yaml` suffix, say) leaves the scan clean over less, and one git stops
    tracking is a workflow that still runs and is no longer anybody's to review.
    """
    globbed = sorted(set(WORKFLOWS.glob("*.yml")) | set(WORKFLOWS.glob("*.yaml")))
    listed = subprocess.run(
        ["git", "ls-files", "-z", "--", "*.yml", "*.yaml"],
        cwd=WORKFLOWS, capture_output=True, text=True, check=True,
    ).stdout
    tracked = set(p for p in listed.split("\0") if p)
    if tracked != set(p.name for p in globbed):
        raise SystemExit(
            "the glob and git disagree about what a workflow is, so one of them"
            f" has been narrowed: {sorted(tracked ^ set(p.name for p in globbed))}"
        )
    return globbed


def main():
    failures = selftest()
    if failures:
        print("the detector itself is broken, so a clean scan would mean nothing:")
        for f in failures:
            print(f"  {f}")
        return 1
    print("detector self-test: ok")

    paths = workflows()
    if not paths:
        print(f"no workflows found under {WORKFLOWS} — the scan would be clean "
              "for the wrong reason")
        return 1

    found, checked = [], 0
    for path in paths:
        lines = path.read_text(encoding="utf-8").splitlines()
        refs = references(path.name, lines)
        checked += len(refs)
        for ref in refs:
            why = violation(ref)
            if why is not None:
                found.append(f"{path.name}:{ref.line}: {why}")
    if not checked:
        print(f"{len(paths)} workflows and not one `uses:` between them — this "
              "guard read something other than the workflows")
        return 1
    if found:
        print("an action runs from a ref that can be moved onto other code, which "
              ".github/dependabot.yml's opening comment is the rule against:")
        for f in found:
            print(f"  {f}")
        return 1
    # The counts are the coverage claim: a scan that narrowed to fewer files or
    # fewer references still prints `ok`, and only these numbers say over what.
    print(f"ok: {checked} `uses:` across {len(paths)} workflows, every one pinned")
    return 0


if __name__ == "__main__":
    sys.exit(main())
