#!/usr/bin/env python3
"""Fail if a workflow runs an action that is not pinned to a commit SHA.

`.github/dependabot.yml` states the rule and the reason: the workflows pin every
action to a commit SHA, because a retargeted `v4` runs attacker-chosen code in a
job that holds a live credential, and Dependabot exists to keep those pins from
rotting. The rule was applied by hand (#96 follow-ups) and kept by memory after
that, so nothing noticed when #472 -- a workflow file generated by the Claude
Code GitHub App installer and merged with both bot reviewers' SHA-pinning
findings unresolved -- put four mutable tags back: `actions/checkout@v4` and
`anthropics/claude-code-action@v1`, twice each, in jobs carrying
`id-token: write` and an OAuth token. Dependabot then did the only thing it
could and offered to move one mutable tag to another (#518). This is the
enforcing half of that fix: the rule now fails a build instead of a reviewer.

WHAT IT CHECKS, which is a SHAPE and not an identity:

  - the ref is a 40-character lowercase hex commit SHA, not a tag or a branch;
  - a trailing comment names a three-part release (`# v7.0.1`). NOT because
    Dependabot needs one -- it refreshes a bare SHA pin perfectly well, and has
    rewritten the version comment alongside since 2022 -- but because a reader
    does: forty hex characters say nothing about what is running, so without the
    comment the diff that moves an action is unreviewable. Every other pin in
    this repository carries one. A two-part or bare-major comment is refused
    deliberately: `# v7` names a moving pointer, not the release the SHA is.

WHAT IT CANNOT SEE, stated plainly so the surrounding prose claims no more:

  - whether the SHA IS the release its comment names. That needs the network,
    which a gate cannot have; a comment reading `# v7.0.1` beside some other
    project's commit passes here. Dependabot rewrites the comment when it moves
    a pin, which keeps the two aligned most of the time and not all of it -- it
    has open cases where the comment goes stale. So that pairing is a habit, not
    a proof, and review is what closes this one.
  - whether the pinned commit deserves trust. A pin freezes code; it does not
    review it, and freezing is also how a workflow keeps running a stale action
    long after upstream fixed something in it. That is the cost the pairing with
    Dependabot buys back, and the reason a pin without an updater is worse than
    no pin at all.
  - `persist-credentials: false`, the companion clause of the same policy. Three
    `actions/checkout` call sites lack it today (#558), so a rule for it would go
    red on work this guard is not about. It needs its own change, and that issue
    is where the decision lives -- a docstring can explain a deferral but cannot
    track one.
  - anything outside `.github/workflows/`: a composite action's own `uses:`, or a
    reusable workflow held in another repository.

IT READS THE TEXT, NOT THE PARSED YAML. Half the rule lives in a COMMENT, and a
parsed `uses:` can say `owner/repo@<sha>` while saying nothing about which
release that SHA is. That is a trade rather than a necessity, and it is worth
naming the other side: a comment-preserving parser, or a structural parse
correlated back to the source, would both do this properly. Both are a
dependency, and the stdlib has no YAML parser at all -- so the guards in this
directory read text, and the paragraph below is what that costs.

WHAT COUNTS AS A `uses:` AT ALL, since reading text means deciding that here.
A step's `uses:` is a mapping KEY, so the scan anchors on key position: `uses:`
opening a line, with or without the `- ` that opens a list item. The token in
any other position is a value -- `grep -n "uses:" file` in a `run:` line is the
one this repository is most likely to write -- and is none of this guard's
business. That leaves one shape anchoring alone would walk past: a step written
in YAML flow style (`steps: [{uses: owner/repo@v4}]`) is a real step in a
position the anchor does not reach, so a token followed by something that reads
as an action reference is refused by name rather than skipped, wherever it sits.

EXEMPTIONS, recorded rather than discovered later. Two `uses:` forms can never
carry a commit SHA -- a local action or reusable workflow (`./…`) and a container
(`docker://…`) -- so both pass. Neither exists in this repository today, which
means a guard that flagged them would look correct forever and then go red on the
first legitimate one. A `docker://` image is not required to carry a digest here;
that would be a different rule about a different supply chain.

WHAT IT REFUSES THAT IS NEVERTHELESS VALID, recorded rather than worked around.
Reading text means drawing a line, and the line belongs in writing. Each of
these is loud and says what to do instead, which is the trade this guard takes
over quietly certifying something it cannot read:

  - an input literally named `uses` under a step's `with:`, indistinguishable
    from a step key without tracking which block a line sits in;
  - a step whose `uses:` is a YAML ALIAS (`uses: *checkout`). Actions has
    supported anchors since September 2025, and an alias resolves nowhere in
    the text and carries no release comment at the use site;
  - a step written in flow style (`steps: [{uses: …}]`), for the same reason;
  - an UPPERCASE SHA, which resolves to the same commit and is refused anyway --
    two spellings of one pin is one too many, and Dependabot rewrites only the
    one it wrote.

AND WHAT COULD STILL SLIP PAST, because the count this prints is a coverage
claim and not a proof: a `uses:` in some shape neither the key anchor nor the
reference search recognises is walked over in silence. Both were widened by
review already -- a quoted key, a space before the colon, a flow mapping, a `#`
smuggled into a ref -- and neither is a closed set. The remedy for that class is
the next reviewer, not another regex.

It self-tests before it scans, because a broken pattern and a clean repository
print the same thing otherwise, and it refuses rather than skips: a line naming
something that looks like an action, which this parser cannot place, stops the
run by name and line instead of passing silently over it.
"""

import pathlib
import re
import subprocess
import sys

WORKFLOWS = pathlib.Path(__file__).resolve().parents[1] / "workflows"

# A `uses:` mapping key, in both spellings that occur: the list-item form that
# opens a step (`- uses: …`) and the keyed form that follows a `- name:` line.
# Anchoring on only the first misses every reference in the two workflows this
# guard was written for, which are all the second.
USES_KEY = re.compile(r"^(?P<indent>[ \t]*)(?:-[ \t]+)?uses:[ \t]*(?P<value>\S.*?)[ \t]*$")

# Deliberately looser, and it must stay that way: it matches the key-position
# spellings USES_KEY cannot parse -- a quoted key, a space before the colon, a
# value on the following line -- so each is reported by name rather than skipped.
USES_CANDIDATE = re.compile(r"^[ \t]*(?:-[ \t]+)?[\"']?uses[\"']?[ \t]*:")

# An action reference away from key position, which is the one thing the anchor
# above must not be trusted to cover: a flow-style step (`steps: [{uses: …}]`)
# is a real step, and walking past one is how this guard would report `ok` over
# an unpinned action. The lookbehind keeps `causes:` out of it.
STRAY_REFERENCE = re.compile(
    r"(?<![A-Za-z0-9_])uses[\"']?[ \t]*:[ \t]*[\"']?(?P<value>[\w.-]+/[\w./-]+@\S+)"
)

# Any key introducing a literal or folded block scalar, not just `run:`. The
# workflows use three (`run:`, `if:`, `additional_permissions:`), and the
# constraint is the same for all of them: their body is data, not YAML mapping
# keys, so a `uses:` inside one is text rather than a step.
#
# `lead` spans the `- ` of a list item deliberately. The body of `- run: |` is
# what is indented past the KEY, not past the dash: measuring to the dash makes
# every sibling key of that step (`uses:`, `with:`, `env:`) look like body, and
# a real reference then disappears into a block scalar that never existed.
BLOCK_SCALAR = re.compile(
    r"^(?P<lead>[ \t]*(?:-[ \t]+)?)[A-Za-z_][\w.-]*[ \t]*:[ \t]*[|>][-+0-9]*[ \t]*(?:#.*)?$"
)

# An action reference that can be pinned: `owner/repo@ref`, with the optional
# subdirectory a composite action or a remote reusable workflow adds.
REFERENCE = re.compile(r"^(?P<action>[\w.-]+/[\w./-]+)@(?P<ref>\S+)$")

# The pin itself. Lowercase because that is what git writes and what every
# existing pin here is; an uppercase SHA resolves fine but would make two
# spellings of one pin, and Dependabot rewrites only the one it wrote.
SHA = re.compile(r"^[0-9a-f]{40}$")

# The release the SHA is. Three parts, anchored at the start of the comment so
# trailing prose is allowed but a leading excuse is not.
RELEASE = re.compile(r"^#[ \t]*v\d+\.\d+\.\d+(?![\w.])")

# The two forms with no SHA to pin. Neither occurs here yet; see the docstring.
EXEMPT = ("./", "docker://")


class Reference:
    """One `uses:` key: where it is, what it names, and what follows it."""

    def __init__(self, line, value, comment):
        self.line = line
        self.value = value
        self.comment = comment


def split_comment(text):
    """A line's value and its trailing comment, by YAML's own rule for `#`.

    A `#` opens a comment only at the start of a line or after whitespace, and
    never inside a quoted scalar. Both halves are load-bearing rather than
    pedantic, and splitting on the first `#` instead is a way to certify a
    mutable tag as a pin: `#` is a legal character in a git ref --
    git-check-ref-format forbids a long list and not this one -- so

        uses: "owner/action@<40 hex>#v1.2.3"

    reaches Actions as one ref naming a TAG, while a naive split reads a
    40-character SHA with a tidy release comment sitting beside it.
    """
    quote = ""
    for i, ch in enumerate(text):
        if quote:
            if ch == quote:
                quote = ""
        elif ch in "\"'":
            quote = ch
        elif ch == "#" and (i == 0 or text[i - 1] in " \t"):
            return text[:i].rstrip(), text[i:].strip()
    return text.rstrip(), ""


def in_block_scalar(lines):
    """The indexes of lines sitting inside a block scalar's body."""
    inside, i = set(), 0
    while i < len(lines):
        m = BLOCK_SCALAR.match(lines[i])
        if not m:
            i += 1
            continue
        # The body is everything more-indented than the KEY, blank lines
        # included, up to the first line that returns to the key's column.
        key_indent = len(m.group("lead"))
        j = i + 1
        while j < len(lines):
            line = lines[j]
            if line.strip() and len(line) - len(line.lstrip()) <= key_indent:
                break
            inside.add(j)
            j += 1
        i = j
    return inside


def reads_as_reference(code):
    """Does this line name something that would be an action reference?"""
    m = USES_KEY.match(code)
    if m:
        value = m.group("value").strip("\"'")
        if value.startswith(EXEMPT) or REFERENCE.match(value):
            return True
    return bool(STRAY_REFERENCE.search(code))


def references(name, lines):
    """Every action reference in one workflow, refusing what it cannot place."""
    body = in_block_scalar(lines)
    found = []
    for n, line in enumerate(lines):
        code, comment = split_comment(line)
        where = f"{name}:{n + 1}"
        if n in body:
            # A `uses:` in block-scalar text is shell or an expression, not a
            # step -- unless it reads as a real reference, in which case the
            # likelier reading by far is that this parser lost its place, and
            # a reference it never checked is exactly what it exists to prevent.
            if reads_as_reference(code):
                raise SystemExit(
                    f"{where}: this reads as an action reference but sits inside a"
                    " block scalar, where this guard would never check it. Either"
                    " the block-scalar scan has lost its place, or a workflow is"
                    " writing a workflow — in which case say so here."
                )
            continue
        if not USES_CANDIDATE.match(code):
            # Not a step key. Only one thing here can still be a step: a
            # reference in flow style, which the anchor cannot reach.
            if STRAY_REFERENCE.search(code):
                raise SystemExit(
                    f"{where}: this names an action away from the `uses:` key this"
                    " guard reads, so its pin would go UNCHECKED. Write the step in"
                    " block style, or teach USES_CANDIDATE the new shape."
                )
            continue
        m = USES_KEY.match(code)
        if not m:
            raise SystemExit(
                f"{where}: this names `uses:` in a shape this guard cannot read,"
                " so its pin would go UNCHECKED. Spell it the way the other steps"
                " are, or teach USES_KEY the new shape."
            )
        found.append(Reference(n + 1, m.group("value").strip("\"'"), comment))
    return found


def violation(ref):
    """Why this reference is not an acceptable pin, or None if it is one."""
    if ref.value.startswith(EXEMPT):
        return None
    m = REFERENCE.match(ref.value)
    if not m:
        return f"`{ref.value}` is not an action reference this guard can pin-check"
    if not SHA.match(m.group("ref")):
        return (f"`{m.group('action')}` is pinned to `{m.group('ref')}`, a mutable"
                " ref — a tag or branch can be retargeted onto other code")
    if not RELEASE.match(ref.comment):
        return (f"`{m.group('action')}` is pinned to a commit but names no release"
                " — add a trailing `# vX.Y.Z`, without which forty hex characters"
                " say nothing about what runs and the pin cannot be reviewed")
    return None


def scan(name, text):
    """One workflow's violations, as (line, why)."""
    return [(r.line, why) for r in references(name, text.splitlines())
            if (why := violation(r)) is not None]


def selftest():
    """Prove each rule fires and each exemption holds. Documents, not prose.

    The rows are a sample: a rule narrowed to some shape none of them names
    still passes every one. What they prove is that each rule is wired in and
    each exemption is deliberate — and, for the refusals, that a reference this
    parser cannot place stops the run rather than leaving CI green over it.
    """
    step = "    steps:\n      - name: a step\n"
    must_flag = [
        ("a mutable major tag, list-item form",
         "      - uses: actions/checkout@v4\n"),
        ("a mutable major tag, keyed form",
         step + "        uses: anthropics/claude-code-action@v1\n"),
        ("a mutable release tag, which looks pinned and is not",
         "      - uses: actions/checkout@v7.0.1 # v7.0.1\n"),
        ("a branch",
         "      - uses: anthropics/claude-code-action@main\n"),
        ("a short SHA",
         "      - uses: actions/checkout@3d3c42e5 # v7.0.1\n"),
        ("an uppercase SHA, which is a second spelling of one pin",
         "      - uses: actions/checkout@3D3C42E5AAC5BA805825DA76410C181273BA90B1 # v7.0.1\n"),
        ("a SHA with no release named",
         "      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1\n"),
        ("a SHA whose comment names a moving pointer, not a release",
         "      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7\n"),
        ("a SHA whose comment names a two-part version",
         "      - uses: helm/kind-action@ef37e7f390d99f746eb8b610417061a60e82a6cc # v1.14\n"),
        ("a comment that explains before it names the release",
         "      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # pinned, v7.0.1\n"),
        # The sibling key of a list-item block scalar. Measuring the body from
        # the dash rather than the key swallowed this whole step, and a real
        # unpinned action went with it.
        ("a step whose sibling key opens a block scalar",
         "      - if: >\n          github.event_name == 'push'\n        uses: actions/checkout@v4\n"),
        # `#` is legal in a git ref, so both of these reach Actions as ONE ref
        # naming a tag. Splitting on the first `#` instead reads a 40-character
        # SHA with a tidy release comment beside it, and certifies the tag.
        ("a hash smuggled into a quoted ref",
         '      - uses: "evil/action@3d3c42e5aac5ba805825da76410c181273ba90b1#v1.2.3"\n'),
        ("a hash smuggled into an unquoted ref",
         "      - uses: evil/action@3d3c42e5aac5ba805825da76410c181273ba90b1#v1.2.3\n"),
    ]
    must_pass = [
        ("a pinned action, list-item form",
         "      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1\n"),
        ("a pinned action, keyed form",
         step + "        uses: anthropics/claude-code-action@fa2b2666b747000bf42767d1f332065b375e3c8f # v1.0.214\n"),
        ("a pinned action, quoted",
         '      - uses: "actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1" # v7.0.1\n'),
        ("a release comment with prose after it",
         "      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1, see #96\n"),
        ("a remote reusable workflow, which pins like an action",
         "    uses: o/r/.github/workflows/w.yml@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1\n"),
        ("a local action, which has no SHA to pin",
         "      - uses: ./.github/actions/thing\n"),
        ("a local reusable workflow",
         "    uses: ./.github/workflows/reusable.yml\n"),
        ("a container, which pins by a different mechanism",
         "      - uses: docker://alpine:3.20\n"),
        ("a pinned step whose sibling key opens a block scalar",
         "      - if: >\n          github.event_name == 'push'\n"
         "        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1\n"),
        ("shell text inside a block scalar",
         "      - run: |\n          grep uses: x.yml\n"),
        # The line this repository is most likely to write, and an early draft
        # aborted the whole run on it while claiming `run:` was out of scope.
        ("the token in a single-line shell value",
         '      - run: grep -n "uses:" .github/workflows/ci.yml\n'),
        ("a word ending in the token, in code position",
         "      - run: echo causes: x\n"),
        ("a comment that merely contains the token",
         "      # it names both causes: this cannot\n"),
        ("a folded block scalar's body",
         "      - if: >\n          contains(github.event.uses: no)\n"),
        ("a block scalar the next key closes",
         "      - run: |\n          echo uses: nothing\n      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1\n"),
    ]
    # Shapes that must stop the run rather than pass or be counted. Each was a
    # way for a reference to go unchecked while the scan still printed `ok`.
    must_refuse = [
        ("a reference this parser cannot place",
         "      - uses:\n          - actions/checkout@v4\n"),
        ("a quoted key, which USES_KEY does not read",
         '      - "uses": actions/checkout@v4\n'),
        ("a space before the colon, which USES_KEY does not read",
         "      - uses : actions/checkout@v4\n"),
        ("a step written in flow style, which the key anchor cannot reach",
         "    steps: [{uses: actions/checkout@v4}]\n"),
        ("a real reference the block-scalar scan swallowed",
         "      - run: |\n          uses: actions/checkout@v4\n"),
        ("a local action the block-scalar scan swallowed",
         "      - run: |\n          uses: ./.github/actions/thing\n"),
        # A comment after the block-scalar header is valid YAML. A header this
        # scan fails to recognise turns its body into mapping keys, which reads
        # as a finding in a file that has none.
        ("a block scalar whose header carries a comment",
         "      - run: | # why\n          uses: actions/checkout@v4\n"),
    ]

    failures = []
    for label, text in must_flag:
        try:
            if not scan("selftest.yml", text):
                failures.append(f"MISSED   {label}: {text.strip()}")
        except SystemExit as e:
            failures.append(f"REFUSED  {label}: expected a finding, got {e}")
    for label, text in must_pass:
        try:
            found = scan("selftest.yml", text)
            if found:
                failures.append(f"FLAGGED  {label}: {found}")
        except SystemExit as e:
            failures.append(f"REFUSED  {label}: expected a clean scan, got {e}")
    for label, text in must_refuse:
        try:
            scan("selftest.yml", text)
            failures.append(f"ACCEPTED {label}: expected a refusal, got none")
        except SystemExit:
            pass

    # The parser must also SEE what it passes, or an exemption and a blind spot
    # are the same result. The first must_pass row is one step and one reference.
    seen = len(references("selftest.yml", must_pass[0][1].splitlines()))
    if seen != 1:
        failures.append(f"COUNT    a single pinned step read as {seen} references")
    return failures


def workflows():
    """The workflow files, listed twice over so a NARROWING of the glob fails.

    The glob is what the scan walks; git is what the repository says is there,
    and the asymmetry between them is deliberate. A file git tracks that the
    glob no longer matches is how this guard dies quietly -- a `.yaml` dropped
    from the pattern leaves the scan printing `ok` over less -- so that
    direction is fatal. The other direction is not a narrowing at all: a
    workflow written and not yet `git add`ed is work in progress, and failing
    that run with an accusation of narrowing teaches a reader to distrust the
    message. It is scanned along with the rest.
    """
    globbed = sorted(set(WORKFLOWS.glob("*.yml")) | set(WORKFLOWS.glob("*.yaml")))
    listed = subprocess.run(
        ["git", "ls-files", "-z", "--", "*.yml", "*.yaml"],
        cwd=WORKFLOWS, capture_output=True, text=True, check=True,
    ).stdout
    tracked = set(p for p in listed.split("\0") if p)
    missed = sorted(tracked - set(p.name for p in globbed))
    if missed:
        raise SystemExit(
            "git tracks workflows this scan's glob does not match, so the glob has"
            f" been narrowed and they would go unchecked: {missed}"
        )
    return globbed


def main():
    failures = selftest()
    if failures:
        print("the detector itself is broken, so a clean scan would mean nothing:")
        for f in failures:
            print(f"  {f}")
        return 1
    print("detector self-test: ok")

    paths = workflows()
    if not paths:
        print(f"no workflows found under {WORKFLOWS} — the scan would be clean "
              "for the wrong reason")
        return 1

    found, checked = [], 0
    for path in paths:
        lines = path.read_text(encoding="utf-8").splitlines()
        refs = references(path.name, lines)
        checked += len(refs)
        for ref in refs:
            why = violation(ref)
            if why is not None:
                found.append(f"{path.name}:{ref.line}: {why}")
    if not checked:
        print(f"{len(paths)} workflows and not one `uses:` between them — this "
              "guard read something other than the workflows")
        return 1
    if found:
        print("an action runs from a ref that can be moved onto other code, which "
              ".github/dependabot.yml's opening comment is the rule against:")
        for f in found:
            print(f"  {f}")
        return 1
    # The counts are the coverage claim: a scan that narrowed to fewer files or
    # fewer references still prints `ok`, and only these numbers say over what.
    print(f"ok: {checked} `uses:` across {len(paths)} workflows, every one pinned")
    return 0


if __name__ == "__main__":
    sys.exit(main())
