-- 0001_init: core schema.
--
-- Conventions:
--   * IDs are prefixed text values (agent_…, env_…, sesn_…, sevt_…, work_…)
--     generated by internal/domain; the database stores them opaquely.
--   * Every top-level resource table reserves org_id / workspace_id /
--     project_id with single-tenant defaults, so multi-tenancy can land
--     without changing the meaning of existing rows. Scoping is
--     org/workspace/project — never an end-user. agent_versions inherits
--     its scope from the parent agent row.
--   * created_at/updated_at are maintained by the application.

CREATE TABLE agents (
    id           text PRIMARY KEY,
    org_id       text NOT NULL DEFAULT 'default',
    workspace_id text NOT NULL DEFAULT 'default',
    project_id   text NOT NULL DEFAULT 'default',
    name         text NOT NULL,
    -- Optimistic lock, starts at 1; every update bumps it and snapshots a
    -- row into agent_versions.
    version      integer NOT NULL DEFAULT 1,
    spec         jsonb NOT NULL, -- AgentSpec: model/system/tools/mcp_servers/skills/multiagent
    metadata     jsonb NOT NULL DEFAULT '{}',
    created_at   timestamptz NOT NULL DEFAULT now(),
    updated_at   timestamptz NOT NULL DEFAULT now(),
    archived_at  timestamptz
);

-- Immutable per-version snapshots; sessions resolve against one of these.
CREATE TABLE agent_versions (
    agent_id   text NOT NULL REFERENCES agents(id) ON DELETE CASCADE,
    version    integer NOT NULL,
    name       text NOT NULL,
    spec       jsonb NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (agent_id, version)
);

CREATE TABLE environments (
    id           text PRIMARY KEY,
    org_id       text NOT NULL DEFAULT 'default',
    workspace_id text NOT NULL DEFAULT 'default',
    project_id   text NOT NULL DEFAULT 'default',
    name         text NOT NULL,
    kind         text NOT NULL CHECK (kind IN ('cloud', 'self_hosted')),
    -- Lifecycle state; no CHECK because the wire schema does not pin its
    -- values (the current SDK expresses lifecycle via archived_at only).
    state        text,
    -- On the wire the cloud/self_hosted discriminator lives INSIDE config
    -- (a tagged union); the kind column denormalizes it for queries and the
    -- CHECK below keeps the two from ever disagreeing. No default: a config
    -- without a type cannot round-trip.
    config       jsonb NOT NULL,
    description  text NOT NULL DEFAULT '', -- required plain string on the wire
    metadata     jsonb NOT NULL DEFAULT '{}',
    created_at   timestamptz NOT NULL DEFAULT now(),
    updated_at   timestamptz NOT NULL DEFAULT now(),
    archived_at  timestamptz,
    -- IS NOT DISTINCT FROM: a config missing 'type' yields SQL NULL, which
    -- a plain = comparison would wave through the CHECK.
    CONSTRAINT environments_kind_config_agree CHECK ((config->>'type') IS NOT DISTINCT FROM kind)
);

CREATE TABLE sessions (
    id             text PRIMARY KEY,
    org_id         text NOT NULL DEFAULT 'default',
    workspace_id   text NOT NULL DEFAULT 'default',
    project_id     text NOT NULL DEFAULT 'default',
    agent_id       text NOT NULL,
    agent_version  integer NOT NULL,
    -- ResolvedAgent snapshot applied to this session (after per-session
    -- overrides); agent updates never retroactively change a live session.
    resolved_agent jsonb NOT NULL,
    environment_id text NOT NULL REFERENCES environments(id),
    status         text NOT NULL DEFAULT 'idle'
                   CHECK (status IN ('idle', 'running', 'rescheduling', 'terminated')),
    title          text NOT NULL DEFAULT '', -- required plain string on the wire
    metadata       jsonb NOT NULL DEFAULT '{}',
    usage          jsonb NOT NULL DEFAULT '{}',
    resources      jsonb NOT NULL DEFAULT '[]',
    vault_ids      text[] NOT NULL DEFAULT '{}', -- reserved seam; vaults are post-v1
    -- Audit only: which API key / principal created the session. Never part
    -- of the wire schema, never used for isolation. Sessions carry no
    -- user_id by design.
    created_by     text,
    created_at     timestamptz NOT NULL DEFAULT now(),
    updated_at     timestamptz NOT NULL DEFAULT now(),
    -- Sessions pin an immutable snapshot row, so the audit trail from a
    -- session to the exact spec that produced it can never dangle. (The
    -- agents row is implied via agent_versions' own FK.)
    FOREIGN KEY (agent_id, agent_version) REFERENCES agent_versions (agent_id, version)
);

CREATE INDEX sessions_agent_idx ON sessions (agent_id);

-- Append-only event log: the single source of truth for session state.
-- Immutability is an event-store invariant (slice 3); the schema-level
-- guarantee is one monotonic seq per session.
CREATE TABLE events (
    id           text PRIMARY KEY,
    org_id       text NOT NULL DEFAULT 'default',
    workspace_id text NOT NULL DEFAULT 'default',
    project_id   text NOT NULL DEFAULT 'default',
    session_id   text NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
    seq          bigint NOT NULL,
    thread_id    text, -- multi-agent seam; wire name is session_thread_id
    type         text NOT NULL,
    payload      jsonb NOT NULL,
    processed_at timestamptz,
    created_at   timestamptz NOT NULL DEFAULT now(),
    UNIQUE (session_id, seq)
);

CREATE TABLE work_items (
    id               text PRIMARY KEY,
    org_id           text NOT NULL DEFAULT 'default',
    workspace_id     text NOT NULL DEFAULT 'default',
    project_id       text NOT NULL DEFAULT 'default',
    environment_id   text NOT NULL REFERENCES environments(id) ON DELETE CASCADE,
    session_id       text NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
    kind             text NOT NULL CHECK (kind IN ('model_turn', 'tool_exec')),
    state            text NOT NULL DEFAULT 'queued'
                     CHECK (state IN ('queued', 'starting', 'active', 'stopping', 'stopped')),
    lease_expires_at timestamptz,
    last_heartbeat   timestamptz,
    metadata         jsonb NOT NULL DEFAULT '{}',
    created_at       timestamptz NOT NULL DEFAULT now(),
    updated_at       timestamptz NOT NULL DEFAULT now()
);

-- Poll order: oldest queued work first, per environment.
CREATE INDEX work_items_poll_idx ON work_items (environment_id, state, created_at);
-- Supports the session_id cascade (and slice 6's per-session work lookups);
-- without it every session delete seq-scans the queue.
CREATE INDEX work_items_session_idx ON work_items (session_id);

-- Management-plane credentials (x-api-key). Only the hash is stored;
-- revoked_at supports rotation.
CREATE TABLE api_keys (
    id           text PRIMARY KEY,
    org_id       text NOT NULL DEFAULT 'default',
    workspace_id text NOT NULL DEFAULT 'default',
    project_id   text NOT NULL DEFAULT 'default',
    name         text NOT NULL,
    key_hash     text NOT NULL UNIQUE,
    created_at   timestamptz NOT NULL DEFAULT now(),
    revoked_at   timestamptz
);

-- Worker credentials (Authorization: Bearer), each scoped to exactly one
-- environment's work queue.
CREATE TABLE environment_keys (
    id             text PRIMARY KEY,
    org_id         text NOT NULL DEFAULT 'default',
    workspace_id   text NOT NULL DEFAULT 'default',
    project_id     text NOT NULL DEFAULT 'default',
    environment_id text NOT NULL REFERENCES environments(id) ON DELETE CASCADE,
    key_hash       text NOT NULL UNIQUE,
    created_at     timestamptz NOT NULL DEFAULT now(),
    revoked_at     timestamptz
);
