-- The agent-archive refusal's own index (#523). Archiving an agent is refused
-- while a live deployment pins it (plan 37 decision 7), and naming the blockers
-- runs, inside archiveAgent's transaction:
--
--   SELECT id, count(*) OVER () FROM deployments
--    WHERE agent_id = $1 AND archived_at IS NULL
--    ORDER BY created_at, id LIMIT 5
--
-- 0031's deployments_agent_idx is on agent_id alone, so that read sorted its
-- matches and returned to the heap to test archived_at. Where an agent's
-- deployments are a small share of the table — the case worth planning for —
-- that measures as Limit -> Sort -> WindowAgg -> Bitmap Heap Scan; where one
-- agent owns much of it, the planner walks deployments_created_idx instead and
-- filters, which loses the sort but reads the table. Carrying the ordering
-- columns and the predicate here makes it Limit -> WindowAgg -> Index Only Scan,
-- and it is preferred over both.
--
-- What this does not change is the order of growth. count(*) OVER () reads every
-- matching row whatever index serves it, so the LIMIT still bounds the output
-- and not the work, and archiveAgent holds FOR UPDATE on the agent row while it
-- runs, so deployment creates and repins of that agent queue behind it. The
-- work is O(live deployments pinning one agent) before and after; this is the
-- constant.
--
-- deployments_agent_idx is deliberately kept, for the one caller this index
-- cannot serve: GET /v1/deployments?agent_id=&include_archived=true drops the
-- archived_at predicate, and a partial index cannot answer a query over rows it
-- excludes. The default listing keeps the predicate and is served by this index
-- instead.
--
-- "Index only" is the plan node, not a promise about the heap: an index-only
-- scan still fetches from it for rows the visibility map does not mark, so the
-- archive that follows a bulk repin reads some. The sort and the predicate are
-- what this index removes unconditionally.
--
-- Not CONCURRENTLY: migrate.go applies every pending file inside one
-- transaction, and CREATE INDEX CONCURRENTLY cannot run in a transaction block.
-- This form takes ACCESS EXCLUSIVE on deployments for the build. store.Open
-- migrates at process start, so the process running it is not yet serving —
-- but on a rolling upgrade the replicas still on the old version are, and their
-- reads of this table wait. No ceiling on the table's size is claimed here to
-- argue that away: the reference's published 1,000
-- cap is on *scheduled* deployments per organization (docs/DIVERGENCES.md, where
-- it is also recorded as unenforced by this platform), and a manual deployment
-- carries no schedule, so nothing bounds the live rows this index spans.
--
-- 0031's comment on deployments_agent_idx gives the archive check as its
-- reason. That reason moves here; 0031 is merged and cannot say so itself.
CREATE INDEX deployments_agent_live_idx
    ON deployments (agent_id, created_at, id) WHERE archived_at IS NULL;
